# Generated by Django 4.2 on 2024-09-25 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_user_update_time_alter_user_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passsword',
            new_name='password',
        ),
    ]
