# Generated by Django 4.2 on 2024-09-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_rename_passsword_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sys_account',
            },
        ),
    ]
